### ISSUE TITLE
ValueError: time data '03-14-19' does not match format '%m/%d/%y'

### ISSUE THREAD

**Issue by TBWarrington** [chatcannon/galvani#20]
Hello,
I'm getting a ValueError from the date pulled by BioLogic.py. The weird thing is it worked on files generated yesterday but not today, and we haven't changed anything. I believe the data file was generated by version 11.02 of EC-labs. The full error is below. Thanks!

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/FREDsense/automated_analysis/WebFrontEnd.py", line 84, in ec_assay
    output = runAnalysis(file_filenames, timestamp)
  File "/home/FREDsense/automated_analysis/scripts/Peak_Analysis.py", line 92, in runAnalysis
    mpr = MPRfile(filename)
  File "/home/FREDsense/.local/lib/python3.7/site-packages/galvani/BioLogic.py", line 353, in __init__
    tm = time.strptime(str3(settings_mod['date']), '%m/%d/%y')
  File "/usr/lib/python3.7/_strptime.py", line 571, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '03-14-19' does not match format '%m/%d/%y'

**Comment by chatcannon** [comment]
Is there any chance you could send me one of the files that aren't working?

**Comment by TBWarrington** [comment]
Here is a file that doesn't work: C019P-0ppb-A_C01.mpr All my files from
that day don't appear to work. I have also included files from the day
before and the day after that seem to work fine. All files were produced
with the same setup.

**Comment by TBWarrington** [comment]
Not sure the files I attached to the email came through. Here they are again:
C019P-0ppb-A_C01.mpr is the one that doesn't work. None from that day seemed to work. Files from before and after that day seem to work fine even though all were created with the same setup.

[BioLogic_Files.zip](https://github.com/chatcannon/galvani/files/2989210/BioLogic_Files.zip)
